[tool.ruff]
line-length = 88
target-version = "py311"
exclude = [
    ".git",
    ".mypy_cache",
    ".pre-commit-cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "venv",
    "docs",
    "__pycache__",
    "**/migrations/*",
]

[tool.ruff.lint]
extend-select = ["B"]  # Enable flake8-bugbear rules

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"]  # Ignore 'assert' statement warnings in test files
